
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab3(
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,
	input 		     [1:0]		KEY,
	output reg	     [9:0]		LEDR,
	input 		     [9:0]		SW
);
 wire [9:0] SWR;

 simple_debouncer bouncer (.clk(MAX10_CLK1_50), .button_in(SW[9:0]), .button_out(SWR[9:0]));
 //assign SWR = SW;
reg Z;

reg [3:0]state;
reg [3:0] nextstate;

localparam S0 = 4'd0;
localparam S1 = 4'd1;
localparam S2 = 4'd2;
localparam S3 = 4'd3;
localparam S4 = 4'd4;
localparam S5 = 4'd5;
localparam S6 = 4'd6;
localparam S7 = 4'd7;
localparam S8 = 4'd8;

always @(posedge MAX10_CLK1_50 or negedge KEY[0])
begin
if(!KEY[0]) begin
state <= S0;
end else begin 
state <= nextstate;
end
end






always @(state, SWR) begin
 LEDR[9:0]=0;
 LEDR[9:0]=Z;

case(state)
S0:begin
if(SWR[3]) begin
nextstate = S1;
Z=0;
end else begin 
nextstate = S0;


Z=0;
end
end


S1:begin
if(SWR[9:0] == 10'b0000000000) begin // 
nextstate = S2;
Z=0;
end 
else if (SWR[3]) begin
	nextstate = S1;

	Z = 0;
 end 
 else begin 
 
nextstate = S0;
Z=0;
end
end


S2:begin
if(SWR[8]) begin
nextstate = S3;
Z=0;
end
else if (SWR[9:0] == 10'b0000000000) begin
	nextstate = S2;
	Z = 0;
 end 
else begin 
nextstate = S0;
Z=0;
end
end

S3:begin
if(SWR[9:0] == 10'b0000000000) begin
nextstate = S4;
Z=0;
end else if (SWR[8]) begin
	nextstate = S3;
	Z = 0;
 end 

else begin 
nextstate = S0;
Z=0;
end
end

S4:begin
if(SWR[4]) begin
nextstate = S5;

Z=0;
end
else if (SWR[9:0] == 10'b0000000000) begin
	nextstate = S4;
	Z = 0;
 end 
 else begin 
 
nextstate = S0;
Z=0;
end
end

S5:begin
if(SWR[9:0] == 10'b0000000000) begin
nextstate = S6;
Z=0;
end 
else if (SWR[4]) begin
	nextstate = S5;
	Z = 0;
 end 
else begin 
 
nextstate = S0;
Z=0;
end
end

S6:begin
if(SWR[3]) begin
nextstate = S7;
Z=1;
end 
else if (SWR[9:0] == 10'b0000000000) begin
	nextstate = S6;
	Z = 0;
 end 
else begin 
nextstate = S0;
Z=0;
end
end

S7:begin
if(SWR[9:0] == 10'b0000000000) begin
nextstate = S8;
Z=1;
end
else if (SWR[3]) begin
	nextstate = S7;
	Z = 1;
 end 
 else begin 
nextstate = S0;
Z=0;
end
end

S8:begin
if(SWR[9:0] != 10'b0000000000) begin
nextstate = S0;
Z=0;
end
else if (SWR[9:0] == 10'b0000000000) begin
nextstate = S8;
Z = 1;
 end 
 else begin 
nextstate = S0;
end
end

default: begin 
nextstate = S0;
Z=0;
end
endcase
end 






endmodule
